### PR TITLE
docs: update permissions and provisioning

### PR DESCRIPTION
**Pull request by gwdawson**
when implementing the app token auth, i forgot to add the required permissions to the documentation. this pr lists all required permissions when using github app auth

this pr also updates the provisioning section of the docs to include app auth examples.

Before (permissions):
https://grafana.com/docs/plugins/grafana-github-datasource/latest/setup/token/#permissions

After (permissions):
Screenshot 2024-10-01 at 11 17 04

Before (provisioning):
https://grafana.com/docs/plugins/grafana-github-datasource/latest/setup/provisioning/ 

After (provisioning):
Screenshot 2024-10-01 at 12 31 44

Fixes https://github.com/grafana/github-datasource/issues/370

### CODE REVIEW

**Comment by zoltanbedi** [comment]
This looks good.

Can you please also update the readme.md? Can you also please add an example for provisioning? That way we can close this issue #370

**Comment by zoltanbedi** [comment]
In the readme can you please update this section as well? https://github.com/grafana/github-datasource?tab=readme-ov-file#access-token-permissions and also remove the first question from the faq? Thanks 🙏

**Comment by gwdawson** [comment]
@zoltanbedi as discussed in slack, i have removed all the duplicated documentation from the readme.

**Review by zoltanbedi — APPROVED** [review]
LGTM, thank you ⭐

**Pull request merged**
