### PR TITLE
Pull Requests: Add additional user fields

### PR DESCRIPTION
**Pull request by rayfaddis**
Adds more user fields to Pull Requests:

1. Authors name
2. Merged by users name
3. Merged by users login\username
4. Merged by users email
5. Merged by users company name

### CODE REVIEW

**Comment by rayfaddis** [comment]
Hello, can I please get a build run approved for this? @zoltanbedi maybe that's a request to you?

**Review by ivanahuckova — APPROVED** [review]
Hi @rayfaddis! Thank you so much for this contribution. 🫶 The PR looks good. I am going to merge it, but in the future, could you please also include tests for new functionality.

**Comment by rayfaddis** [comment]
Hello @ivanahuckova! and thank you for the reply. I had updated [pkg/github/testdata/pull_requests.golden.jsonc](https://github.com/grafana/github-datasource/pull/286/files#diff-b9304d424229a35b29215d6040c1c916bdf17766fc6a28bd1104cc7b1d45d68c) and didn't see any other tests areas or test data to update. If there is an area where I could have added more tests please let me know, I am new to go.

**Comment by ivanahuckova** [comment]
@rayfaddis oh yeah, you are correct. I thought we have some unit tests in `pkg/github/pull_requests_test.go`, but it seems that we use mainly snapshot tests. So feel free to ignore the part about the additional tests. 🙂

**Pull request merged**
