### PR TITLE
Split rates and counts for runs

### PR DESCRIPTION
**Pull request by orensbruli**

### CODE REVIEW

**Comment by zoltanbedi** [comment]
Hey @orensbruli,
Thank you for opening this pr. can you please fix the test?

**Comment by b0bcarlson** [comment]
I have some alerting I'd like to do that this would enable. I'd love to fix the test but I don't know Go :(

**Comment by ivanahuckova** [comment]
@orensbruli this unfortunately breaks backward compatibility. Could you keep the original fields and add a new ones for rate and count.

**Review by ivanahuckova — CHANGES_REQUESTED** [review]
This breaks backward compatibility, we should keep the original fields and add a new ones for rate and count.

**Comment by ivanahuckova** [comment]
Closing this as there is no activity, but feel free to reopen, if you plan to continue working on this one. 🙂

**Pull request closed without merging**
